# Use the official PHP with Apache as the base image
FROM ubuntu:latest

# Set the working directory in the container
WORKDIR /var/www/html



# Update packages and install necessary dependencies
RUN apt-get update && apt-get install -y \
    nginx \
    openssl \
    php-fpm \
    php-mysql \
    php-zip \
    unzip

# Copy Nginx configuration
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

RUN docker-php-ext-install pdo_mysql zip

# Enable Apache SSL module
RUN a2enmod ssl
# Generate a self-signed SSL certificate
RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/server.key -out /etc/ssl/certs/server.crt \
    -subj "/C=US/ST=NY/L=DixHills/O=GordonWD/CN=gordon.local"
# Copy the Apache virtual host configuration
COPY apache/default-ssl.conf /etc/apache2/sites-available/default-ssl.conf



# Enable the Apache SSL virtual host
RUN a2ensite default-ssl

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Copy the Laravel app code to the container
COPY . .

# Install Laravel dependencies
RUN composer install --no-interaction --optimize-autoloader --no-dev

# Set permissions for Laravel storage and bootstrap/cache directories
RUN chown -R www-data:www-data storage bootstrap/cache
RUN chmod -R 775 storage bootstrap/cache

# Expose port 80
EXPOSE 80

# Start Apache server
CMD ["apache2-foreground"]
